# Generated by Django 5.0.2 on 2024-02-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoflixuser',
            name='verification_code',
            field=models.CharField(blank=True, default='mV6deuHAKRXP2nVq64JbA0sCRgELa5', max_length=30, unique=True),
        ),
    ]
