# Generated by Django 5.0.2 on 2024-02-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoflixuser',
            name='verification_code',
            field=models.CharField(blank=True, default='iFIjbxMxJy1gFWIb83l7HRUFfP0q4Y', max_length=30),
        ),
        migrations.AddField(
            model_name='videoflixuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
