# Generated by Django 5.0.2 on 2024-02-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_videoflixuser_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoflixuser',
            name='verification_code',
            field=models.CharField(blank=True, default='WVgjNDz9nuhiDWNiGMknhqch9YLClD', max_length=30),
        ),
    ]
