# Generated by Django 5.0.2 on 2024-02-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_videoflixuser_reset_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoflixuser',
            name='verification_code',
            field=models.CharField(blank=True, default='fL3UCp8nMpE4LC4iaFPK0XBqxu2fUO', max_length=30, unique=True),
        ),
    ]
