# Generated by Django 5.0.2 on 2024-02-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_videoflixuser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoflixuser',
            name='verification_code',
            field=models.CharField(blank=True, default='1ri8hAmNljzhoQ7HVA94H1DStPb6Bh', max_length=30, unique=True),
        ),
    ]
