# Generated by Django 5.0.2 on 2024-02-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_videoflixuser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoflixuser',
            name='verification_code',
            field=models.CharField(blank=True, default='QnyIet2i5YssaqjZd7YvQwAXdny66H', max_length=30, unique=True),
        ),
    ]
