# Generated by Django 5.0.2 on 2024-02-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_videoflixuser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoflixuser',
            name='verification_code',
            field=models.CharField(blank=True, default='yK4ow3OQ8Nd5xln5sY6v3QlB1O068a', max_length=30, unique=True),
        ),
    ]
