# Generated by Django 5.0.2 on 2024-02-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_videoflixuser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoflixuser',
            name='verification_code',
            field=models.CharField(blank=True, default='Vf0Kw0i5Roje2Xev2moIfzjM0AK6lQ', max_length=30, unique=True),
        ),
    ]
