# Generated by Django 5.0.2 on 2024-02-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_videoflixuser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoflixuser',
            name='verification_code',
            field=models.CharField(blank=True, default='ldpCi0SKZJjo6MgzEWjDLlWMnjN6jr', max_length=30, unique=True),
        ),
    ]
