# Generated by Django 5.0.2 on 2024-02-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_videoflixuser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoflixuser',
            name='verification_code',
            field=models.CharField(blank=True, default='5IA6n4RfQmnDFT17J419EXNajXRH7A', max_length=30, unique=True),
        ),
    ]
