# Generated by Django 5.0.2 on 2024-02-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_videoflixuser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoflixuser',
            name='verification_code',
            field=models.CharField(blank=True, default='x7HTDz1DSx8rhfoBtluB85PUFYQfxK', max_length=30, unique=True),
        ),
    ]
