# Generated by Django 5.0.2 on 2024-02-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_videoflixuser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoflixuser',
            name='verification_code',
            field=models.CharField(blank=True, default='fGv2CcgoVjssfp9WXmZLwraf9IUgit', max_length=30, unique=True),
        ),
    ]
