# Generated by Django 5.0.2 on 2024-02-11 16:35

import video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnails')),
                ('original_video', models.FileField(upload_to=video.models.get_upload_path)),
                ('video_720p', models.FileField(blank=True, null=True, upload_to=video.models.get_upload_path)),
                ('video_480p', models.FileField(blank=True, null=True, upload_to=video.models.get_upload_path)),
            ],
        ),
    ]
