# Generated by Django 5.0.2 on 2024-02-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(upload_to='thumbnails'),
        ),
    ]
