# Generated by Django 5.0.2 on 2024-02-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('mv', 'movie'), ('se', 'series')], max_length=2),
        ),
    ]
