# Generated by Django 5.0.2 on 2024-02-26 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_movie_series_remove_video_category_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='video.series'),
        ),
    ]
