# Generated by Django 5.0.2 on 2024-02-26 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_series_thumbnail_alter_episode_series'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
