# Generated by Django 5.0.2 on 2024-02-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_rename_series_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
