# Generated by Django 5.0.2 on 2024-02-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_alter_serie_title_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='thumbnail',
            field=models.FileField(upload_to='thumbnails'),
        ),
    ]
